services:
  #Equipe 1 : La base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: market_postgres_db
    environment:
      POSTGRES_USER: yann_mle
      POSTGRES_PASSWORD: market_secure_password
      POSTGRES_DB: market_risk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d # Exécute automatiquement nos scripts SQL au démarrage

  airflow-webserver: 
    image: apache/airflow:2.7.2-python3.10
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080" 
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas yfinance sqlalchemy psycopg2-binary scikit-learn
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - DB_USER=yann_mle
      - DB_PASSWORD=market_secure_password
      - DB_NAME=market_risk_db
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./airflow.db:/opt/airflow/airflow.db
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - db


  airflow-scheduler:
    image: apache/airflow:2.7.2-python3.10
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas yfinance sqlalchemy psycopg2-binary scikit-learn
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - DB_USER=yann_mle
      - DB_PASSWORD=market_secure_password
      - DB_NAME=market_risk_db
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./airflow.db:/opt/airflow/airflow.db
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - airflow-webserver
      - db

volumes:
  postgres_data:
